### ISSUE TITLE
v2 TODO list

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/decently-smart-target#7]
- [x] npm module
- [x] use package.json properly
- [x] modular
- [x] global option (dist)
- [x] vanilla javascript
- [x] address localhost:[port] in readme
